-- This file contains the definitive schema for the audit_logs table.
-- It is managed by the application code in `src/shared/storage/auditStore.js`.
-- Do not edit this file manually; it is updated from the source code.

CREATE TABLE IF NOT EXISTS audit_logs (
  recommendation_id VARCHAR(255) PRIMARY KEY,
  customer_id VARCHAR(255) NOT NULL,
  employee_id VARCHAR(255),
  user_role VARCHAR(255),
  traceparent VARCHAR(255),
  input_json JSON NOT NULL,
  decision_json JSON NOT NULL,
  compliance_json JSON NOT NULL,
  advisory_json JSON NOT NULL,
  metadata_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_customer (customer_id),
  INDEX idx_audit_created (created_at),
  INDEX idx_audit_employee (employee_id),
  INDEX idx_audit_role (user_role)
);
